[package]
name = "maratui"
version = "0.1.0"
edition = "2024"

[features]
default = ["device"]
# Build for ESP. cargo build / cargo build --release
device = ["dep:esp-idf-svc", "dep:ili9341", "dep:display-interface-spi", "dep:embuild"]
# Build UI on host. cargo sim --target <host>
simulator = ["dep:embedded-graphics-simulator"]

[dependencies]
anyhow = "1.0.100"
display-interface-spi = { version = "0.5.0", optional = true }
embedded-graphics-simulator = { version = "0.8.0", optional = true }
esp-idf-svc = { version = "0.51", features = ["critical-section"], optional = true }
ili9341 = { version = "0.6.0", optional = true }
libc = "0.2"
log = "0.4.29"
mousefood = { version = "0.4.0", default-features=false, features = ["fonts"] }
ratatui = {version = "0.30.0", default-features = false}
strum = "0.27.2"
strum_macros = "0.27.2"
tui-widgets = {version = "0.7.0", default-features=false, features=["big-text"]}

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"], optional = true }

[profile.release]
opt-level = 3

[profile.dev]
debug = true
opt-level = 3


