[package]
name = "maratui"
version = "0.1.0"
edition = "2024"

[dependencies]
display-interface-spi = "0.5.0"
esp-idf-svc = { version = "0.51", features = ["critical-section"] }
ili9341 = "0.6.0"
libc = "0.2"
log = "0.4"
mousefood = {path = "/home/ololonly/git/mousefood/mousefood" }
ratatui-widgets = "0.3.0"
ratatui-core = "0.1.0"
strum = "0.27.2"
strum_macros = "0.27.2"
tinyqoi = "0.2.0"
tui-big-text = "=0.7.0"

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"] }

[profile.release]
opt-level = "z"

[profile.dev]
debug = true
opt-level = "z"
